<?php
/**
 * IBM_Customer module
 *
 * @copyright Copyright (c) 2022 IBM Inc.
 */
?>
<div id="root-pdp-react-delivery-time"></div>
<div id="root-pdp-react-selectsource"></div>
<div id="root-pdp-react-select-delivery-method"></div>

<script type="text/javascript">
    require(['jquery', 'OMS_Appbuilder/js/setshippingrate-checkout'], function ($, setShippingRateCheckout) {

    });
</script>